study_prefix = "irae"

[file_config.file_names]
# -----------------------------------------------------------------------------
## Upload CSV/TSV curated files
"file_upload.toml" = [
    "file_upload.toml"
]
