study_prefix = "irae"

[file_config]
file_names = [
    "athena/irae__include_study_period.sql",
    "athena/irae__include_utilization.sql",
    "athena/irae__include_age_at_visit.sql",
    "athena/irae__include_enc_class.sql",
    "athena/irae__include_gender.sql",
    "athena/irae__include_race.sql",
    "athena/irae__cohort_study_period.sql",
    "athena/irae__cohort_study_population.sql",
    "athena/irae__cohort_study_population_dx.sql",
    "athena/irae__cohort_study_population_rx.sql",
    "athena/irae__cohort_study_population_lab.sql",
    "athena/irae__cohort_study_population_proc.sql",
    "athena/irae__cohort_study_population_doc.sql",
    "athena/irae__cohort_study_population_diag.sql",
    "athena/irae__meta_date.sql",
    "athena/irae__meta_version.sql",
    "athena/irae__doc_ontology.sql",
    "athena/irae__doc_ontology_kind.sql",
    "athena/irae__doc_ontology_role.sql",
    "athena/irae__doc_ontology_service.sql",
    "athena/irae__doc_ontology_domain.sql",
    "athena/irae__doc_ontology_include.sql",
    "athena/irae__dx_transplant_kidney.sql",
    "athena/irae__dx_transplant_solid_organ.sql",
    "athena/irae__dx_transplant_stem_cell.sql",
    "athena/irae__dx_transplant_recipient.sql",
    "athena/irae__dx_transplant.sql",
    "athena/irae__dx_cancer_melanoma_malignant.sql",
    "athena/irae__dx_cancer.sql",
    "athena/irae__dx_kidney_condition.sql",
    "athena/irae__dx_kidney_renal_disease.sql",
    "athena/irae__dx_kidney_esrd.sql",
    "athena/irae__dx_kidney_ckd.sql",
    "athena/irae__dx_kidney_akf.sql",
    "athena/irae__dx_kidney_dialysis.sql",
    "athena/irae__dx_kidney_nephrotic_syndrome.sql",
    "athena/irae__dx_kidney.sql",
    "athena/irae__dx_autoimmune_inflammatory.sql",
    "athena/irae__dx_autoimmune_ibd.sql",
    "athena/irae__dx_autoimmune_crohns.sql",
    "athena/irae__dx_autoimmune_arthritis_ra.sql",
    "athena/irae__dx_autoimmune_lupus.sql",
    "athena/irae__dx_autoimmune.sql",
    "athena/irae__dx_immunocompromised_any.sql",
    "athena/irae__dx_immunocompromised.sql",
    "athena/irae__dx_infection_bacterial.sql",
    "athena/irae__dx_infection_pna.sql",
    "athena/irae__dx_infection_cmv.sql",
    "athena/irae__dx_infection_rsv.sql",
    "athena/irae__dx_infection_hsv.sql",
    "athena/irae__dx_infection_influenza.sql",
    "athena/irae__dx_infection_shingles.sql",
    "athena/irae__dx_infection_hepatitis_b.sql",
    "athena/irae__dx_infection_hepatitis_c.sql",
    "athena/irae__dx_infection.sql",
    "athena/irae__rx_immunosuppressive_drugs.sql",
    "athena/irae__rx_immunosuppressive_systemic_therapy.sql",
    "athena/irae__rx_immunosuppressive_immune_modulators.sql",
    "athena/irae__rx_immunosuppressive_coricosteroids_systemic.sql",
    "athena/irae__rx_immunosuppressive.sql",
    "athena/irae__rx_cancer_chemo_advanced.sql",
    "athena/irae__rx_cancer_checkpoint.sql",
    "athena/irae__rx_cancer_keytruda.sql",
    "athena/irae__rx_cancer_ade_neutropenia.sql",
    "athena/irae__rx_cancer.sql",
    "athena/irae__rx_antibiotics_any.sql",
    "athena/irae__rx_antibiotics_systemic.sql",
    "athena/irae__rx_antibiotics.sql",
    "athena/irae__rx_diabetes_drugs.sql",
    "athena/irae__rx_diabetes.sql",
    "athena/irae__rx_htn_drugs.sql",
    "athena/irae__rx_htn.sql",
    "athena/irae__rx_diuretics_loop.sql",
    "athena/irae__rx_diuretics_potassium.sql",
    "athena/irae__rx_diuretics_thiazide.sql",
    "athena/irae__rx_diuretics.sql",
    "athena/irae__lab_cbc_with_diff.sql",
    "athena/irae__lab_cbc.sql",
    "athena/irae__lab_cmp_comprehensive.sql",
    "athena/irae__lab_cmp.sql",
    "athena/irae__lab_gfr_egfr.sql",
    "athena/irae__lab_gfr.sql",
    "athena/irae__lab_lft_function.sql",
    "athena/irae__lab_lft_ggt.sql",
    "athena/irae__lab_lft_pt.sql",
    "athena/irae__lab_lft_inr.sql",
    "athena/irae__lab_lft.sql",
    "athena/irae__lab_creatinine_serum_cr.sql",
    "athena/irae__lab_creatinine_blood_cr.sql",
    "athena/irae__lab_creatinine_urine_cr.sql",
    "athena/irae__lab_creatinine_urine_alb_cr_ratio.sql",
    "athena/irae__lab_creatinine_urine_protein_cr_ratio.sql",
    "athena/irae__lab_creatinine_cystatin_c.sql",
    "athena/irae__lab_creatinine.sql",
    "athena/irae__lab_autoimmune_serum_rf.sql",
    "athena/irae__lab_autoimmune_blood_esr.sql",
    "athena/irae__lab_autoimmune_crp.sql",
    "athena/irae__lab_autoimmune_tsh.sql",
    "athena/irae__lab_autoimmune_t3.sql",
    "athena/irae__lab_autoimmune_t4.sql",
    "athena/irae__lab_autoimmune.sql",
    "athena/irae__lab_diabetes_screening.sql",
    "athena/irae__lab_diabetes_glucose_test.sql",
    "athena/irae__lab_diabetes.sql",
    "athena/irae__proc_transplant_kidney.sql",
    "athena/irae__proc_transplant_other_major.sql",
    "athena/irae__proc_transplant_solid_organ.sql",
    "athena/irae__proc_transplant_stem_cell.sql",
    "athena/irae__proc_transplant_recipient.sql",
    "athena/irae__proc_transplant.sql",
    "athena/irae__proc_dialysis_services.sql",
    "athena/irae__proc_dialysis.sql",
    "athena/irae__proc_nephrectomy_sct.sql",
    "athena/irae__proc_nephrectomy_icd10pcs.sql",
    "athena/irae__proc_nephrectomy.sql",
    "athena/irae__doc_biopsy_kidney.sql",
    "athena/irae__doc_biopsy_skin.sql",
    "athena/irae__doc_biopsy_lung.sql",
    "athena/irae__doc_biopsy_bone.sql",
    "athena/irae__doc_biopsy_muscle.sql",
    "athena/irae__doc_biopsy.sql",
    "athena/irae__lab_albumin_urine.sql",
    "athena/irae__lab_azathioprine.sql",
    "athena/irae__lab_azathioprine_tpmt_gene.sql",
    "athena/irae__lab_c_peptide.sql",
    "athena/irae__lab_cyclosporin.sql",
    "athena/irae__lab_cytomegalovirus.sql",
    "athena/irae__lab_gad.sql",
    "athena/irae__lab_gfr_custom.sql",
    "athena/irae__lab_glucose.sql",
    "athena/irae__lab_hdl.sql",
    "athena/irae__lab_hemoglobin_a1c.sql",
    "athena/irae__lab_hla.sql",
    "athena/irae__lab_insulin.sql",
    "athena/irae__lab_ketone_urine.sql",
    "athena/irae__lab_ldl.sql",
    "athena/irae__lab_mycophenolate.sql",
    "athena/irae__lab_sirolimus.sql",
    "athena/irae__lab_tacrolimus.sql",
    "athena/irae__lab_triglyceride.sql",
    "athena/irae__rx_alemtuzumab.sql",
    "athena/irae__rx_atg.sql",
    "athena/irae__rx_azathioprine.sql",
    "athena/irae__rx_basiliximab.sql",
    "athena/irae__rx_belatacept.sql",
    "athena/irae__rx_cyclosporin.sql",
    "athena/irae__rx_cytogam.sql",
    "athena/irae__rx_everolimus.sql",
    "athena/irae__rx_ig.sql",
    "athena/irae__rx_ivig.sql",
    "athena/irae__rx_methylprednisolone.sql",
    "athena/irae__rx_mycophenolate.sql",
    "athena/irae__rx_prednisolone.sql",
    "athena/irae__rx_prednisone.sql",
    "athena/irae__rx_rituximab.sql",
    "athena/irae__rx_sirolimus.sql",
    "athena/irae__rx_tacrolimus.sql",
    "athena/irae__lab_custom.sql",
    "athena/irae__rx_custom.sql",
    "athena/irae__cohort_doc_biopsy.sql",
    "athena/irae__cohort_dx_autoimmune.sql",
    "athena/irae__cohort_dx_cancer.sql",
    "athena/irae__cohort_dx_immunocompromised.sql",
    "athena/irae__cohort_dx_infection.sql",
    "athena/irae__cohort_dx_kidney.sql",
    "athena/irae__cohort_dx_transplant.sql",
    "athena/irae__cohort_lab_autoimmune.sql",
    "athena/irae__cohort_lab_cbc.sql",
    "athena/irae__cohort_lab_cmp.sql",
    "athena/irae__cohort_lab_creatinine.sql",
    "athena/irae__cohort_lab_diabetes.sql",
    "athena/irae__cohort_lab_gfr.sql",
    "athena/irae__cohort_lab_lft.sql",
    "athena/irae__cohort_proc_dialysis.sql",
    "athena/irae__cohort_proc_nephrectomy.sql",
    "athena/irae__cohort_proc_transplant.sql",
    "athena/irae__cohort_rx_antibiotics.sql",
    "athena/irae__cohort_rx_cancer.sql",
    "athena/irae__cohort_rx_diabetes.sql",
    "athena/irae__cohort_rx_diuretics.sql",
    "athena/irae__cohort_rx_htn.sql",
    "athena/irae__cohort_rx_immunosuppressive.sql",
    "athena/irae__cohort_lab_custom.sql",
    "athena/irae__cohort_rx_custom.sql",
    "athena/irae__cohort_study_variables.sql",
    "athena/irae__cohort_study_variables_wide.sql",
    "athena/irae__cohort_study_variables_timeline.sql",
    "athena/irae__casedef_custom_csv.sql",
    "athena/irae__casedef.sql",
    "athena/irae__cohort_casedef.sql",
    "athena/irae__cohort_casedef_exclude.sql",
    "athena/irae__cohort_casedef_include.sql",
    "athena/irae__cohort_casedef_index.sql",
    "athena/irae__cohort_casedef_pre.sql",
    "athena/irae__cohort_casedef_post.sql",
    "athena/irae__cohort_casedef_timeline.sql",
    "athena/irae__sample_casedef_index.sql",
    "athena/irae__sample_casedef_index_10.sql",
    "athena/irae__sample_casedef_index_100.sql",
    "athena/irae__sample_casedef_pre.sql",
    "athena/irae__sample_casedef_pre_10.sql",
    "athena/irae__sample_casedef_pre_100.sql",
    "athena/irae__sample_casedef_post.sql",
    "athena/irae__sample_casedef_post_10.sql",
    "athena/irae__sample_casedef_post_100.sql",
    "athena/irae__count_patient_study_population.sql",
    "athena/irae__count_encounter_study_population.sql",
    "athena/irae__count_patient_study_population_dx.sql",
    "athena/irae__count_encounter_study_population_dx.sql",
    "athena/irae__count_patient_study_population_rx.sql",
    "athena/irae__count_encounter_study_population_rx.sql",
    "athena/irae__count_patient_study_population_lab.sql",
    "athena/irae__count_encounter_study_population_lab.sql",
    "athena/irae__count_patient_study_population_doc.sql",
    "athena/irae__count_document_study_population_doc.sql",
    "athena/irae__count_patient_study_population_proc.sql",
    "athena/irae__count_encounter_study_population_proc.sql",
    "athena/irae__count_patient_study_variables.sql",
    "athena/irae__count_encounter_study_variables.sql",
    "athena/irae__count_patient_dx_transplant.sql",
    "athena/irae__count_patient_dx_cancer.sql",
    "athena/irae__count_patient_dx_kidney.sql",
    "athena/irae__count_patient_dx_autoimmune.sql",
    "athena/irae__count_patient_dx_immunocompromised.sql",
    "athena/irae__count_patient_dx_infection.sql",
    "athena/irae__count_patient_rx_immunosuppressive.sql",
    "athena/irae__count_patient_rx_cancer.sql",
    "athena/irae__count_patient_rx_antibiotics.sql",
    "athena/irae__count_patient_rx_diabetes.sql",
    "athena/irae__count_patient_rx_htn.sql",
    "athena/irae__count_patient_rx_diuretics.sql",
    "athena/irae__count_patient_lab_cbc.sql",
    "athena/irae__count_patient_lab_cmp.sql",
    "athena/irae__count_patient_lab_gfr.sql",
    "athena/irae__count_patient_lab_lft.sql",
    "athena/irae__count_patient_lab_creatinine.sql",
    "athena/irae__count_patient_lab_autoimmune.sql",
    "athena/irae__count_patient_lab_diabetes.sql",
    "athena/irae__count_patient_proc_transplant.sql",
    "athena/irae__count_patient_proc_dialysis.sql",
    "athena/irae__count_patient_proc_nephrectomy.sql",
    "athena/irae__count_patient_doc_biopsy.sql",
    "athena/irae__count_patient_rx_custom.sql",
    "athena/irae__count_patient_lab_custom.sql",
    "athena/irae__count_patient_casedef_timeline.sql",
    "athena/irae__count_encounter_casedef_timeline.sql",
    "athena/irae__count_patient_sample_casedef_pre.sql",
    "athena/irae__count_document_sample_casedef_pre.sql",
    "athena/irae__count_document_sample_casedef_pre_10.sql",
    "athena/irae__count_document_sample_casedef_pre_100.sql",
    "athena/irae__count_patient_sample_casedef_index.sql",
    "athena/irae__count_document_sample_casedef_index.sql",
    "athena/irae__count_document_sample_casedef_index_10.sql",
    "athena/irae__count_document_sample_casedef_index_100.sql",
    "athena/irae__count_patient_sample_casedef_post.sql",
    "athena/irae__count_document_sample_casedef_post.sql",
    "athena/irae__count_document_sample_casedef_post_10.sql",
    "athena/irae__count_document_sample_casedef_post_100.sql",
    "nlp_result_to_highlights/builder_irae_highlights_immunosuppressive_medications.py",
    "nlp_result_to_highlights/builder_irae_highlights_multiple_transplant_history.py",
    "nlp_result_to_highlights/builder_irae_highlights_donor.py",
    "nlp_result_to_highlights/builder_irae_highlights_longitudinal.py",
]

[export_config]
count_list = [
    "irae__count_patient_study_population",
    "irae__count_encounter_study_population",
    "irae__count_patient_study_population_dx",
    "irae__count_encounter_study_population_dx",
    "irae__count_patient_study_population_rx",
    "irae__count_encounter_study_population_rx",
    "irae__count_patient_study_population_lab",
    "irae__count_encounter_study_population_lab",
    "irae__count_patient_study_population_doc",
    "irae__count_document_study_population_doc",
    "irae__count_patient_study_population_proc",
    "irae__count_encounter_study_population_proc",
    "irae__count_patient_study_variables",
    "irae__count_encounter_study_variables",
    "irae__count_patient_dx_transplant",
    "irae__count_patient_dx_cancer",
    "irae__count_patient_dx_kidney",
    "irae__count_patient_dx_autoimmune",
    "irae__count_patient_dx_immunocompromised",
    "irae__count_patient_dx_infection",
    "irae__count_patient_rx_immunosuppressive",
    "irae__count_patient_rx_cancer",
    "irae__count_patient_rx_antibiotics",
    "irae__count_patient_rx_diabetes",
    "irae__count_patient_rx_htn",
    "irae__count_patient_rx_diuretics",
    "irae__count_patient_lab_cbc",
    "irae__count_patient_lab_cmp",
    "irae__count_patient_lab_gfr",
    "irae__count_patient_lab_lft",
    "irae__count_patient_lab_creatinine",
    "irae__count_patient_lab_autoimmune",
    "irae__count_patient_lab_diabetes",
    "irae__count_patient_proc_transplant",
    "irae__count_patient_proc_dialysis",
    "irae__count_patient_proc_nephrectomy",
    "irae__count_patient_doc_biopsy",
    "irae__count_patient_rx_custom",
    "irae__count_patient_lab_custom",
    "irae__count_patient_casedef_timeline",
    "irae__count_encounter_casedef_timeline",
    "irae__count_patient_sample_casedef_pre",
    "irae__count_document_sample_casedef_pre",
    "irae__count_document_sample_casedef_pre_10",
    "irae__count_document_sample_casedef_pre_100",
    "irae__count_patient_sample_casedef_index",
    "irae__count_document_sample_casedef_index",
    "irae__count_document_sample_casedef_index_10",
    "irae__count_document_sample_casedef_index_100",
    "irae__count_patient_sample_casedef_post",
    "irae__count_document_sample_casedef_post",
    "irae__count_document_sample_casedef_post_10",
    "irae__count_document_sample_casedef_post_100",
]
flat_list = []
meta_list = [
    "irae__meta_date",
    "irae__meta_version",
]
